### ISSUE TITLE
pop up "need the project password when try to access the Macros"

### ISSUE THREAD

**Issue by mengdahuang** [deepanshu88/MSWord_ChatGPT#1]
Hi, Thanks for your great work first.

i want to try this template but i can not open and edit the Macros. it show need project password.
![image](https://github.com/deepanshu88/MSWord_ChatGPT/assets/32334062/f0047131-b632-4be6-b156-9b5a846bdc84)
 
Is it possible to tell me the password? thanks a lot.

**Comment by deepanshu88** [comment]
You don't need password to install the add-in
